import React,{useEffect,useState}from"react";import{createRoot}from"react-dom/client";import"./styles.css";
const DEFAULT="https://docs.google.com/spreadsheets/d/1I1SInEpn_x_p7QHPGVcpvNmHX613aWPAl-whbLOsQQs/edit?gid=1555120034#gid=1555120034";
const norm=x=>String(x??"").trim().toLowerCase(), id=u=>(String(u).match(/\/spreadsheets\/d\/([^/]+)/)||[])[1]||"";
function parse(t){let a=t.indexOf("{"),b=t.lastIndexOf("}"),j=JSON.parse(t.slice(a,b+1)),c=j.table.cols.map(x=>x.label||"");return{c,r:j.table.rows.map(x=>c.reduce((o,k,i)=>(o[k]=x.c?.[i]?.v??"",o),{}))}}
function col(c,a){return c.find(x=>a.some(y=>norm(x)==norm(y)))}
function App(){let[url,setUrl]=useState(localStorage.url||DEFAULT),[designer,setDesigner]=useState(localStorage.designer||""),[names,setNames]=useState([]),[tasks,setTasks]=useState([]),[choose,setChoose]=useState(!localStorage.designer),[draft,setDraft]=useState(localStorage.designer||""),[settings,setSettings]=useState(false),[error,setError]=useState("");
async function load(){try{let gid=(String(url).match(/[?&#]gid=(\d+)/)||[])[1]||"1555120034",r=await fetch(`https://docs.google.com/spreadsheets/d/${id(url)}/gviz/tq?tqx=out:json&gid=${gid}`);let p=parse(await r.text()),dc=col(p.c,["Designer"]),tc=col(p.c,["Task","Task Name","Name","Title"]),sc=col(p.c,["Status"]),dl=col(p.c,["Deadline","Due Date","Due"]),dt=col(p.c,["Date","Created"]);if(!dc||!tc)throw Error('Sheet must contain "Designer" and Task/Task Name columns.');let ns=[...new Set(p.r.map(x=>String(x[dc]||"").trim()).filter(Boolean))].sort();setNames(ns);setTasks(p.r.filter(x=>x[tc]).map((x,i)=>({id:i,task:String(x[tc]),status:String(sc?x[sc]:""),deadline:String(dl?x[dl]:""),designer:String(x[dc]||"").trim(),date:String(dt?x[dt]:"")})))}catch(e){setError(e.message)}}useEffect(()=>load(),[]);
function path(id,k){return JSON.parse(localStorage["p"+id]||"{}")[k]||""}function setp(id,k,v){let x=JSON.parse(localStorage["p"+id]||"{}");x[k]=v;localStorage["p"+id]=JSON.stringify(x);setTasks([...tasks])}
function useDesigner(){let d=names.find(x=>norm(x)==norm(draft))||draft.trim();if(d){setDesigner(d);localStorage.designer=d;setChoose(false)}}
let visible=tasks.filter(x=>norm(x.designer)==norm(designer));
return <><header><h1>Task Dashboard</h1><div><button onClick={()=>{setDraft(designer);setChoose(true)}}>Designer: {designer||"Select"} ▾</button><button onClick={load}>Refresh</button><button onClick={()=>setSettings(true)}>Settings</button></div></header><main>{error&&<p className="error">{error}</p>}{designer&&<div className="info"><b>{visible.length} tasks</b><span>Current Designer: <b>{designer}</b></span><button onClick={()=>{setDraft(designer);setChoose(true)}}>Change Designer</button></div>}<table><thead><tr><th>Task Name</th><th>Status</th><th>Deadline</th><th>Designer</th><th>Date</th><th>Local Folder / Workfile ZIP</th></tr></thead><tbody>{visible.map(t=><tr key={t.id}><td><b>{t.task}</b></td><td>{t.status||"—"}</td><td>{t.deadline||"—"}</td><td>{t.designer}</td><td>{t.date||"—"}</td><td><div className="files">{["folder","zip"].map(k=><div key={k}><div className="drop" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();let p=e.dataTransfer.files?.[0]?.path;if(p)setp(t.id,k,p)}}>{path(t.id,k)||`Drop ${k=="folder"?"task folder":"workfile ZIP"} here`}</div><button onClick={async()=>{let p=await window.desktop[k]();if(p)setp(t.id,k,p)}}>Browse</button>{path(t.id,k)&&<><button onClick={()=>window.desktop.open(path(t.id,k))}>Open</button><button onClick={()=>window.desktop.explorer(path(t.id,k))}>Explorer</button><button onClick={()=>setp(t.id,k,"")}>Clear</button></>}</div>)}</div></td></tr>)}</tbody></table></main>
{choose&&<div className="modal"><div><h2>Choose Designer</h2><select value={draft}onChange={e=>setDraft(e.target.value)}><option value="">Select designer...</option>{names.map(n=><option key={n}>{n}</option>)}</select><button disabled={!draft}onClick={useDesigner}>Use This Designer</button></div></div>}
{settings&&<div className="modal"><div><h2>Google Sheet Source</h2><p>READ ONLY — never writes to the Google Sheet.</p><input value={url}onChange={e=>setUrl(e.target.value)}/><button onClick={()=>{localStorage.url=url;setSettings(false);load()}}>Save & Refresh</button><button onClick={()=>setSettings(false)}>Cancel</button></div></div>}</>};createRoot(document.getElementById("root")).render(<App/>);